package model.enums;

public enum CustomerStatus {
    INTERESTED,
    INFO_SESSION_INVITED,
    INFO_SESSION_ATTENDED,
    BOOKED,
    ADVISOR_ASSIGNED,
    ONBOARDING,
    MEDICAL_CHECK,
    HOTEL,
    SHUTTLE,
    PRE_FLIGHT,
    FLIGHT,
    LANDING,
    FEEDBACK,
    COMPLETED
}
